export const articles = [
	{
		id: "1",
		title: "How to Cook a Steak",
		description: "A guide on how to cook a perfect steak",
		date: "2023-02-14",
		image: "https://www.example.com/steak.jpg",
	},
	{
		id: "2",
		title: "How to Build a Deck",
		description: "A step-by-step guide on how to build a deck",
		date: "2023-02-11",
		image: "https://www.example.com/deck.jpg",
	},
	{
		id: "3",
		title: "How to Start a Business",
		description: "A guide on how to start a business from scratch",
		date: "2023-02-07",
		image: "https://www.example.com/business.jpg",
	},
	{
		id: "4",
		title: "How to Code in Python",
		description: "A beginner's guide to coding in Python",
		date: "2023-02-18",
		image: "https://www.example.com/python.jpg",
	},
	{
		id: "5",
		title: "How to Fix a Flat Tire",
		description: "A guide on how to fix a flat tire",
		date: "2023-02-16",
		image: "https://www.example.com/flat-tire.jpg",
	},
	{
		id: "6",
		title: "How to Play Tennis",
		description: "A guide on how to play tennis",
		date: "2023-02-13",
		image: "https://www.example.com/tennis.jpg",
	},
	{
		id: "7",
		title: "How to Draw a Portrait",
		description: "A guide on how to draw a portrait",
		date: "2023-02-10",
		image: "https://www.example.com/portrait.jpg",
	},
	{
		id: "8",
		title: "How to Write a Novel",
		description: "A guide on how to write a novel",
		date: "2023-02-06",
		image: "https://www.example.com/novel.jpg",
	},
	{
		id: "9",
		title: "How to Use a Sewing Machine",
		description: "A guide on how to use a sewing machine",
		date: "2023-02-20",
		image: "https://www.example.com/sewing-machine.jpg",
	},
	{
		id: "10",
		title: "How to Cook Pasta",
		description: "A guide on how to cook pasta",
		date: "2023-02-17",
		image: "https://www.example.com/pasta.jpg",
	},
	{
		id: "11",
		title: "How to Build a Website",
		description: "A step-by-step guide on how to build a website",
		date: "2023-02-12",
		image: "https://www.example.com/website.jpg",
	},
	{
		id: "12",
		title: "How to Play Chess",
		description: "A guide on how to play chess",
		date: "2023-02-08",
		image: "https://www.example.com/chess.jpg",
	},
	{
		id: "13",
		title: "How to Draw a Car",
		description: "A guide on how to draw a car",
		date: "2023-02-05",
		image: "https://www.example.com/car.jpg",
	},
	{
		id: "14",
		title: "How to Bake a Cake",
		description: "A guide on how to bake a cake",
		date: "2023-02-22",
		image: "https://www.example.com/cake.jpg",
	},
	{
		id: "15",
		title: "How to Play Guitar",
		description: "A guide on how to play the guitar",
		date: "2023-02-19",
		image: "https://www.example.com/guitar.jpg",
	},
	{
		id: "16",
		title: "How to Write a Resume",
		description: "A guide on how to write a resume",
		date: "2023-02-15",
		image: "https://www.example.com/resume.jpg",
	},
	{
		id: "17",
		title: "How to Paint a Wall",
		description: "A guide on how to paint a wall",
		date: "2023-02-11",
		image: "https://www.example.com/paint.jpg",
	},
	{
		id: "18",
		title: "How to Play Basketball",
		description: "A guide on how to play basketball",
		date: "2023-02-07",
		image: "https://www.example.com/basketball.jpg",
	},
	{
		id: "19",
		title: "How to Draw a Tree",
		description: "A guide on how to draw a tree",
		date: "2023-02-21",
		image: "https://www.example.com/tree.jpg",
	},
	{
		id: "20",
		title: "How to Code in C++",
		description: "A beginner's guide to coding in C++",
		date: "2023-02-23",
		image: "https://www.example.com/cpp.jpg",
	},
];
